### ISSUE TITLE
Command to get the builds for a Pull Request

### ISSUE THREAD

**Issue by jwittner** [Microsoft/vsts-cli#113]
Right now I'm having to filter all of the builds in the list by the value of `system.pullRequest.pullRequestId` in the `parameters` section of build results in order to find the builds associated with a Pull Request. Is this the right way to do this? I'd love if the PR information from `vsts code pr list' included build ids associated with the PR.

Perhaps it does or can and I'm just not seeing it.

**Comment by tedchamb** [comment]
One thing you can do is see the policies associated with your pull request, which includes build ids and status along with other ploicies:

For example:
vsts code pr policies list --id 100

You can then filter out non-build policies using the --query option if you only want to see builds.  This does not however include builds that were associated with your pr but are not associated by a PR policy.

**Comment by jwittner** [comment]
Awesome, that's got the data I needed!
