### ISSUE TITLE
Ability to open (in browser) foo from cli

### ISSUE THREAD

**Issue by rovinbhandari** [Microsoft/vsts-cli#114]
Hello! I find vsts cli quite useful. A feature I would really like to have is 'open' akin to 'show'. While 'show' shows the details of foo (let's say, pr, for example) using its id, 'open' should open the pr in the [default] browser to review. foo could be a work item, a pr, a build, a branch or anything else 'show' supports (or more). Currently, even if I can observe prs or builds from the console, I need to click multiple times and navigate to what I'm interested in. I feel the cli can fill that gap by directly bringing me to my destination with zero clicks involved.

I'm open to submitting a PR for this feature.

**Comment by tedchamb** [comment]
@rovinbhandari , most commands have a --open argument, that will open the browser to the default page of the returned object.

For Example:
vsts code pr create --open
vsts code pr show --id 100 --open
vsts work item show --id 100 --open

**Comment by rovinbhandari** [comment]
Thanks for the reply @tedchamb! I guess I need to sharpen my documentation reading skills. I will try out the --open arguments for my most used VSTS scenarios and add more support if needed.
