### ISSUE TITLE
Automatically detect reviewers

### ISSUE THREAD

**Issue by chillryan** [Microsoft/vsts-cli#123]
When creating a PR on the portal, the reviewer is automatically added (due to some setting I believe). It would be nice if the 'pr create' command would automatically add default reviewers.

**Comment by tedchamb** [comment]
@chillryan  Reviewers set by PR policies will automatically get added to your created PRs.   In the web UI, you are under a team context, and thus the team also gets added to your PR automatically.  On the command line we do not have a team context, so we can't add it.  You can explicitly add the team to the reviewers arg at creation time to work around.
