### ISSUE TITLE
Calling vsts-cli via powershell from a build agent is not recognised 

### ISSUE THREAD

**Issue by tomaustin700** [Microsoft/vsts-cli#124]
Hi,
I have created a powershell script which uses the vsts-cli to generate release notes for our product. This script is part of a TFS on-premise release process. When I run the script manually everything works as planned however when the script is ran as part of the release using the build agent the following error is thrown:

2017-12-22T08:39:04.1947486Z ##[error]vsts : The term 'vsts' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.

The server the agent is on has the vsts-cli installed and configured correctly and as I have said before I can run the script manually and it works correctly. Is there something I am missing here?

Thanks

**Comment by tedchamb** [comment]
@tomaustin700 Add a step to your powershell script that checks your path environment variable.  It sounds like the path to your vsts script is no longer in your path environment variable when in the build powershell script context.

**Comment by tomaustin700** [comment]
@tedchamb Hi, sorry for the late response. Can you give me an example showing how to do that?

**Comment by tedchamb** [comment]
To view the path setting in the build log you can add a line like this to your powershell build script and then run a build and see what the value is:

<code>Write-Host "Path=$Env:path"</code>

If the path to the wbin folder is not there, you can add the vsts cli path to your path environment variable like this:

<code>$Env:path = "$Env:path;$Env:ProgramFiles(x86)\Microsoft SDKs\VSTS\CLI\wbin"</code>

**Comment by tomaustin700** [comment]
@tedchamb Hi Ted. That did work however I did have to code it like this
`$Env:path = "$Env:path;C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\wbin"`

Using `$Env:ProgramFiles(x86)` didn't seem to work for some reason. 

Can you explain why the path wasn't in the path environment variable to begin with? I have never encountered this before.

**Comment by tedchamb** [comment]
@tomaustin700, the build agent should pick up the new path value the first time it restarts after the cli installation.  If your build agent also can't find the ProgramFiles(x86) environment variable , then you may want to ensure you don't have some build task that is changing the environment variables settings to a given state.
