### ISSUE TITLE
Login fails when connecting to TFS instance with self-signed certificate

### ISSUE THREAD

**Issue by germanilia** [Microsoft/vsts-cli#129]
Attempting to login against our local TFS instance which uses a cert signed by an internal/private CA fails. Adding the --debug switch confirms my suspicion that the cert isn't trusted. Is there any way to provide an alternate CA bundle? Or to tell the CLI to accept a specific CA or cert?

urllib3.connectionpool : Retrying (Retry(total=2, connect=3, read=3, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)'),)': /tfs/defaultcollection2/_apis

**Comment by tedchamb** [comment]
@germanilia The instructions to deal with untrusted certs is described in #76.  I see you have mentioned on that thread, that you have tried this, and it didn't work for you.  This is msrest functionality, and we have been able to get this working in each case we have tried.  Can you double check that you used the correct cert and set the correct environment variable in the same cmd window instance you are running vsts from?
