### ISSUE TITLE
no output for vsts-login

### ISSUE THREAD

**Issue by gforceg** [Microsoft/vsts-cli#134]
I am unable to log in (I think) using my PAT. I can't tell whether or not that is the real problem because the vsts-login command returns no output.

expected behavior:

```bash
vsts login --token <some bogus token>
```

I would expect the app to print to stderr, something like "failed to log in. check your credentials."

```bash
vsts login --token <some valid token>
```

I would expect the app to print nothing at all or a success message.

TFX-CLI had the same problem but there was a TFX_TRACE environmental variable.

Can somebody shed some light on why this cli application does not output to std? What gives?

Thanks.

**Comment by tedchamb** [comment]
@gforceg you will get a failure message if the login is not successful.

Use the --debug argument if you want to see all the trace messages.
