### ISSUE TITLE
Please release more often (it is pre-release anyway)

### ISSUE THREAD

**Issue by bergmeister** [Microsoft/vsts-cli#139]
The PowerShell team releases their pre-releases every 3 weeks (and they started doing that already in the early Alpha days).
I see many useful features/improvements being added, please (pre)-release them as well.

**Comment by tedchamb** [comment]
We plan to start releasing on a sprintly cadence, and have nightly dev builds, once we have the infrastructure in place to do this.  We will get to this soon.
