### ISSUE TITLE
Question: How to add multiline description to PR

### ISSUE THREAD

**Issue by Paul-Dempsey** [Microsoft/vsts-cli#145]
The reference docs have no examples to show just how you specify various things on the command line. It definitely needs good examples in order to be less obscure.

How do I create/update a multi-line description using the CLI? (Or is this even possible?)

**Comment by tedchambers** [comment]
A bash shell will allow you to add multiline, but I am not sure of a way to do it with the windows cmd window.  We could possibly change the arg to a list which would allow something like:

--description "line 1" "line 2"

**Comment by Paul-Dempsey** [comment]
The question about multi-line was intended as simply an example of the type of information. I forgot to say "For example". The main point of this issue was intended to be that the CLI needs good practical example of the usage, and there are currently none.

**Comment by tedchamb** [comment]
We hope to invest more in the CLI in the coming months, which would also include making our documentation better.  Until then, your best option for help and information is from the following:

- Using the -h argument to get help on a specific command or find out what commands are avilable
- VSTS CLI docs: https://docs.microsoft.com/en-us/cli/vsts/overview?view=vsts-cli-latest
- We use the knack command line framework, so you may find some useful information from their repo: https://github.com/Microsoft/knack
- ask specific questions here, and we will try and answer them for you.
