### ISSUE TITLE
Feature request: Source/Target branch for "code pr list" command

### ISSUE THREAD

**Issue by arazuvaev** [Microsoft/vsts-cli#146]
Can we add an ability to display source/target branch for `code pr list`?

If you're up for having it implemented, I can create a PR to get it working.

**Comment by tedchamb** [comment]
thanks @arazuvaev , its just a matter of screen real estate.    We want to keep the output width to a size that works for most screens, so if we add them, we may need to get rid of some other columns.  See #80 for request to customize columns, which is currently supported, but customization needs to be specified on each call.  We would like to add a feature where you can specify this customization as the default for a specific command.

**Comment by arazuvaev** [comment]
That totally works, didn't realize `--query` existed 😄This totally addresses all my needs. Thanks!
