### ISSUE TITLE
running any command gives API resource location not registered error on TFS 2017

### ISSUE THREAD

**Issue by arthis** [Microsoft/vsts-cli#149]
Hi 

whenever I try to run any command through vsts cli in my commandline ,

 ```
vsts code pr list --project myProject --instance https://mytfsServerInstance/DefaultCollection
vsts work item create --type bug --title "Typo in docs" --project myProject --instance https://mytfsServerInstance/DefaultCollection
```

 I receive the following error  :

`API resource location 'some-guid'  is not registered on  'https://mytfsServer/DefaultCollection'`

I am using the following tfs server : Version 15.112.26307.0 , Update 1

the version of the cli is  :

```
 vsts --version
vsts-cli (0.1.0b1)

knack (0.2.0)
vsts (0.1.0b1.dev4413677)
vsts-cli-build (0.1.0b1)
vsts-cli-build-common (0.1.0b1)
vsts-cli-code (0.1.0b1)
vsts-cli-code-common (0.1.0b1)
vsts-cli-common (0.1.0b1)
vsts-cli-team (0.1.0b1)
vsts-cli-team-common (0.1.0b1)
vsts-cli-work (0.1.0b1)
vsts-cli-work-common (0.1.0b1)

Python (Windows) 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]

Python location: C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\python.exe

Legal docs and information: https://aka.ms/vsts-cli-eula
```

Thanks

**Comment by tedchamb** [comment]
@arthis, please rerun your command with the --debug argument, and then send me the output after you remove any sensitive data.

Thanks,
Ted

**Comment by arthis** [comment]
Here is the log produced by the command. But I have some feeling it has to do with the internal proxy 


λ vsts code pr list --debug                                                                                                            
Command arguments: ['code', 'pr', 'list', '--debug']                                                                                   
Event: Cli.PreExecute [<function VstsCLI.pre_execute at 0x000000000470C950>]                                                           
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x00000000037D9620>, <function Ou            
tputProducer.on_global_arguments at 0x0000000003810950>, <function CLIQuery.on_global_arguments at 0x0000000003836620>]                
Event: CommandInvoker.OnPreCommandTableCreate [<function CLILogging.remove_logger_flags at 0x00000000037D96A8>]                        
Event: CommandLoader.OnLoadCommandTable []                                                                                             
Event: CommandLoader.OnLoadArguments []                                                                                                
Event: CommandInvoker.OnPostCommandTableCreate []                                                                                      
Event: CommandInvoker.OnCommandTableLoaded []                                                                                          
Event: CommandInvoker.OnPreParseArgs []                                                                                                
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x00000000038109D8>, <function CL            
IQuery.handle_query_parameter at 0x00000000038366A8>]                                                                                  
root : Remote url: https://itfs.yyyyyyy-zzzzzzzz.com/DefaultCollection/InformationSystem4/_git/Developers-MicroSer            
viceScaffold                                                                                                                           
root : Loading cache file: C:\Users\xxxx\.vsts\cli\cache\remotes.json                                                                 
root : attempting to read file C:\Users\xxxxx\.vsts\cli\cache\remotes.json as utf-8-sig                                                
root : Detect: Url discovery took 0:00:00.047000                                                                                       
root : Getting credential: vsts-cli:https://itfs.yyyyyyy-zzzzzzzz.com                                                         
root : Creating connection with personal access token.                                                                                 
root : Telemetry enabled.                                                                                                              
root : Loading cache file: C:\Users\xxxxx\.vsts\python-sdk\cache\options.json                                                          
root : attempting to read file C:\Users\xxxxx\.vsts\python-sdk\cache\options.json as utf-8-sig                                         
root : Cache file does not exist: C:\Users\xxxxx\.vsts\python-sdk\cache\resources.json                                                 
root : File cache hit for options on: https://itfs.yyyyyyy-zzzzzzzz.com/defaultcollection                                     
root : File cache miss for resources on: https://itfs.yyyyyyy-zzzzzzzz.com/defaultcollection                                  
root : File cache hit for options on: https://itfs.yyyyyyy-zzzzzzzz.com/defaultcollection                                     
root : Route template: _apis/{area}/{resource}                                                                                         
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None                                                             
root : API resource location e81700f7-3be2-46de-8624-2eb35882fcaa is not registered on https://itfs.yyyyyyy-zzzzzzzz.com/DefaultCollection.                                                                                                              
Traceback (most recent call last):                                                                                                     
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\code\common\pull_request.py", line 101, i            
n list_pull_requests                                                                                                                   
    client = get_git_client(team_instance)                                                                                             
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\common\services.py", line 84, in get_git_            
client                                                                                                                                 
    return connection.get_client('vsts.git.v4_0.git_client.GitClient')                                                                 
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\vss_connection.py", line 35, in get_client               
    self._client_cache[client_type] = self._get_client_instance(client_class)                                                          
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\vss_connection.py", line 48, in _get_client_i            
nstance                                                                                                                                
    url = self._get_url_for_client_instance(client_class)                                                                              
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\vss_connection.py", line 58, in _get_url_for_            
client_instance                                                                                                                        
    resource_areas = self._get_resource_areas()                                                                                        
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\vss_connection.py", line 88, in _get_resource            
_areas                                                                                                                                 
    self._resource_areas = location_client.get_resource_areas()                                                                        
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\location\v4_0\location_client.py", line 72, i            
n get_resource_areas                                                                                                                   
    returns_collection=True)                                                                                                           
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\vss_client.py", line 65, in _send                        
    query_parameters=query_parameters)                                                                                                 
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\vss_client.py", line 97, in _create_request_m            
essage                                                                                                                                 
    + self.config.base_url + '.')                                                                                                      
ValueError: API resource location e81700f7-3be2-46de-8624-2eb35882fcaa is not registered on https://itfs.yyyyyyy-zzzzzzzz.com/DefaultCollection.                                                                                                         
API resource location e81700f7-3be2-46de-8624-2eb35882fcaa is not registered on https://itfs.yyyyyyy-zzzzzzzz.com/            
DefaultCollection.msrest.pipeline : Configuring redirects: allow=True, max=30                                                          
                                                                                                                                       
msrest.pipeline : Configuring proxies: ''                                                                                              
msrest.pipeline : Evaluate proxies against ENV settings: True                                                                          
msrest.pipeline : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90                                                 
urllib3.connectionpool : Starting new HTTPS connection (1): itfs.yyyyyyy-zzzzzzzz.com                                         
urllib3.connectionpool : https://itfs.yyyyyyy-zzzzzzzz.com:443 "POST /DefaultCollection/_apis/CustomerIntelligence            
/Events HTTP/1.1" 204 0                                                                                                                
msrest.http_logger : Request URL: 'https://itfs.yyyyyyy-zzzzzzzz.com/DefaultCollection/_apis/CustomerIntelligence/            
Events'                                                                                                                                
msrest.http_logger : Request method: 'POST'                                                                                            
msrest.http_logger : Request headers:                                                                                                  
msrest.http_logger :     'User-Agent': 'python/3.6.2 (Windows-7-6.1.7601-SP1) requests/2.18.4 msrest/0.4.18 vsts/0.1.0b0.de            
v4413677 vstscli/0.1.0b0'                                                                                                              
msrest.http_logger :     'Accept-Encoding': 'gzip, deflate'                                                                            
msrest.http_logger :     'Accept': 'application/json;api-version=3.1-preview'                                                          
msrest.http_logger :     'Connection': 'keep-alive'                                                                                    
msrest.http_logger :     'Content-Type': 'application/json; charset=utf-8'                                                             
msrest.http_logger :     'X-TFS-FedAuthRedirect': 'Suppress'                                                                           
msrest.http_logger :     'X-TFS-Session': 'a3e2bc54-5e2e-405f-96b6-e02049a756d1'                                                       
msrest.http_logger :     'Content-Length': '93'                                                                                        
msrest.http_logger :     'Authorization': '*****'                                                                                      
msrest.http_logger : Request body:                                                                                                     
msrest.http_logger : [{"area": "CLI", "feature": "code", "properties": {"Command": "pr list", "Args": ["debug"]}}]                     
msrest.http_logger : Response status: 204                                                                                              
msrest.http_logger : Response headers:                                                                                                 
msrest.http_logger :     'Cache-Control': 'no-cache'                                                                                   
msrest.http_logger :     'Pragma': 'no-cache'                                                                                          
msrest.http_logger :     'Expires': '-1'                                                                                               
msrest.http_logger :     'Server': 'Microsoft-IIS/10.0'                                                                                
msrest.http_logger :     'X-TFS-ProcessId': '345233bb-95f7-4de0-9906-20c45a26c299'                                                     
msrest.http_logger :     'ActivityId': 'b74cc15f-401e-4267-9ce2-38d1f8d33d99'                                                          
msrest.http_logger :     'X-TFS-Session': 'a3e2bc54-5e2e-405f-96b6-e02049a756d1'                                                       
msrest.http_logger :     'X-VSS-E2EID': 'b74cc15f-401e-4267-9ce2-38d1f8d33d99'                                                         
msrest.http_logger :     'X-FRAME-OPTIONS': 'SAMEORIGIN'                                                                               
msrest.http_logger :     'X-VSS-UserData': '37466069-9325-48af-ae50-c6e8295d2ce8:xxxxx'                                                
msrest.http_logger :     'X-AspNet-Version': '4.0.30319'                                                                               
msrest.http_logger :     'Request-Context': 'appId=cid-v1:c3ef53f8-a0c8-49d9-b686-5f203a5f1803'                                        
msrest.http_logger :     'X-Powered-By': 'ASP.NET'                                                                                     
msrest.http_logger :     'P3P': 'CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM I            
NT PHY ONL FIN PUR LOC CNT"'                                                                                                           
msrest.http_logger :     'Lfs-Authenticate': 'NTLM'                                                                                    
msrest.http_logger :     'X-Content-Type-Options': 'nosniff'                                                                           
msrest.http_logger :     'Date': 'Fri, 20 Apr 2018 14:01:25 GMT'                                                                       
msrest.http_logger : Response content:                                                                                                 
msrest.http_logger : b''

**Comment by tedchamb** [comment]
Thanks for sending the details..  What version of TFS 2017 are you targeting?  Can you try deleting the cache for the vsts python sdk, and then running the command again with the --debug option? To do this, you can delete this folder: `C:\Users\xxxxx.vsts\python-sdk\cache`  This will force the cli to fetch the location data again from the server.  Be careful not to post any private data when posting the debug results, or you can send it to me directly.

**Comment by arthis** [comment]
great! it works like a charm. Thanks for your help.
