### ISSUE TITLE
update the doc and include how to install via brew for macOS

### ISSUE THREAD

**Issue by TravisEz13** [Microsoft/vsts-cli#164]
http://brewformulas.org/VstsCli

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29493ec8-b119-457b-21c1-348a6b807884
* Version Independent ID: bf64c389-7811-b33c-6c2a-b8d69a9ec7d3
* Content: [Install the VSTS CLI](https://docs.microsoft.com/en-us/cli/vsts/install?view=vsts-cli-latest)
* Content Source: [latest/docs-ref-conceptual/install.md](https://github.com/MicrosoftDocs/vsts-docs-cli-python/blob/live/latest/docs-ref-conceptual/install.md)
* Product: **vsts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
I've added homebrew instructions for mac :) thank you!
