### ISSUE TITLE
auto-complete does not set work items to be complete

### ISSUE THREAD

**Issue by flcdrg** [Microsoft/vsts-cli#168]
For a repository with a branch policy that requires a work item be attached to the pull request, I would expect that if work items are supplied via --work-item then they would be completed.

`git pr create --auto-complete --delete-source-branch --work-item 331 --open`

However, the PR displays the following status:

`Changes will be merged into master. Branch blahblahblah will be deleted. Work items will be unchanged.`

If that's not the case, then do we need another command line option to indicate that should happen?

**Comment by tedchamb** [comment]
@flcdrg  Thanks for pointing this out.  Yes, we should definitively add that.

**Comment by tedchamb** [comment]
Fixed in dev branch: #171

**Comment by tedchamb** [comment]
The fix is now available in VSTS-CLI 0.1.2
