### ISSUE TITLE
Install & Get started documentation does now mention where tool is installed to

### ISSUE THREAD

**Issue by aeruru** [Microsoft/vsts-cli#197]
This is for the windows installer. It'd be great if the docs explained that the tool is installed to C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI and explain that you need to run the vsts.bat file in the wbin folder.

**Comment by tedchamb** [comment]
@aeruru, thanks for reporting your issue.  The wbin folder is added to your path by the msi.  Unfortunately any existing command windows will not pick up the new path until they are restarted.  

@elbatk can we make this clearer in the docs.

**Comment by aeruru** [comment]
Thanks @tedchamb, that was the issue for me.
