### ISSUE TITLE
Location cache not expiring correctly

### ISSUE THREAD

**Issue by zarenner** [Microsoft/vsts-cli#211]
Due to a bug in vsts-python-api's _file_cache (https://github.com/Microsoft/vsts-python-api/issues/111), the resource location cache is not expired correctly.

Once fixed in vsts-python-api, we need to take the update and ensure the cache works as expected.

**Comment by tedchamb** [comment]
https://github.com/Microsoft/vsts-python-api/releases/tag/0.1.16 has been released with the fix.

**Comment by tedchamb** [comment]
fixing in #212
