### ISSUE TITLE
Allow installation via pip

### ISSUE THREAD

**Issue by dalemyers** [Microsoft/vsts-cli#214]
There are some things that this tool is required for now. An example is publishing universal packages. However, since this tool can't be installed through pip (or some other tool manager), we can't easily automate the installation of it on our machines. 

Being able to run `pip install vsts_cli` or similar would make life significantly simpler.

**Comment by tedchamb** [comment]
You can install by running `pip install vsts-cli`.  I would recommend running that from a sandboxed python environment, so it doesn't have dependency conflicts with other packages.

**Comment by dalemyers** [comment]
That's great. Can we get this added to the docs in that case?

**Comment by elbatk** [comment]
Adding this to the install guide right now, thanks everyone!
