### ISSUE TITLE
CLI way to clone TFVC repo

### ISSUE THREAD

**Issue by teejam2** [Microsoft/vsts-cli#218]
Can I use the vsts CLI tool/REST API to clone TFVC repos?

If no why not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a4158f2-cffe-7161-b1c6-f319320532bc
* Version Independent ID: 941afd22-3445-bc32-cf58-cbfeca7fc2fe
* Content: [Git integration and aliases for the VSTS CLI](https://docs.microsoft.com/en-us/cli/vsts/git?view=vsts-cli-latest)
* Content Source: [latest/docs-ref-conceptual/git.md](https://github.com/MicrosoftDocs/vsts-docs-cli-python/blob/live/latest/docs-ref-conceptual/git.md)
* Product: **vsts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by tedchamb** [comment]
The CLI does not have this functionality.  You mention TFVC repo, but do you mean a git repo? or are you referring to enlisting in TFVC?

**Comment by teejam2** [comment]
Hi,

I was able to do this using the old tf.exe tool and workspaces

Thanks for your help.

**Comment by geverghe** [comment]
Closing this issue as resolved.

**Comment by geverghe** [comment]
Closing this issue as the request has been resolved.
