### ISSUE TITLE
Unable to authenticate with Android Studio

### ISSUE THREAD

**Issue by BismeetSingh** [Microsoft/vsts-cli#233]
I am trying to access this repo https://laqshyainfosoft.visualstudio.com/Edutracker/_git/StudentTracker
I can sign in with credentials on the website but not in android studio.
Studio keeps throwing this window infinitely. I am running Ubuntu 18.10.
![image](https://user-images.githubusercontent.com/13601266/48323423-2b1fa100-e652-11e8-9e7e-4c5715c94a58.png)

**Comment by atbagga** [comment]
This repository only tracks issues with vsts-cli interface. I think the repository you are looking for is this one - https://github.com/Microsoft/azure-devops-intellij

Please look at existing issues and solutions there before filing a issue. :)
