### ISSUE TITLE
package universal download is broken

### ISSUE THREAD

**Issue by eedpWillVinke** [Microsoft/vsts-cli#236]
I am using the Universal package part of this tool as part of a build pipeline, but it has seemed to stop working with your latest commit. Now when I try to push/pull artifacts I get an error that a file is not found. It is unclear, but it looks like the missing file being looked for should be part of the project. Older verisons of your installer do not have this issue. Below is a powershell command and the resulting error output. 

Thanks for your help and convient tool,
                       Will Vinke
__________________________________

`C:\source\develop [develop ≡ +0 ~2 -0 !]> vsts package universal download --instance "https://eedp.visualstudio.com/" --feed "RPackages" --name "r-3.5.0" --version "1.0.1" --path .

Universal Packages is currently in preview.
[WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\knack\invocation.py", line 172, in execute
    cmd_result = parsed_args.func(params)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\knack\commands.py", line 105, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\knack\commands.py", line 203, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\universal.py", line 62, in download_package
    return artifact_tool.download_universal(team_instance, feed, name, version, path)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\artifacttool.py", line 24, in download_universal
    return self.run_artifacttool(team_instance, ["universal", "download", "--service", team_instance, "--patvar", self.PATVAR, "--feed", feed, "--package-name", package_name, "--package-version", package_version, "--path", path], "Downloading")
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\artifacttool.py", line 44, in run_artifacttool
    proc = self._tool_invoker.run(command_args, new_env, initial_progress_message, self._process_stderr)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\external_tool.py", line 68, in run
    self.start(command_args, env)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\external_tool.py", line 38, in start
    env=env)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by atbagga** [comment]
@eedpWillVinke I am unable to repro the issue using vsts-cli version 0.1.3. 

What is the version you are using are you using dev setup since you said.. "but it has seemed to stop working with your latest commit".  Share the --debug logs if the issue is still there.

**Comment by eedpWillVinke** [comment]
I am using vsts-cli version 0.1.3 also. Sorry about the confusion, it does not seem to be a result of the commit (I thought maybe the failed CI build had something to do with it).

Looking more closely it may be a throttling issue or something with the connection to vsts.

Are there download/upload limits associated with Azure Artifacts? 

Thanks for your fast response

`C:\source\develop\lib [develop ≡ +1 ~1 -0 !]> vsts package universal download --instance "https://eedp.visualstudio.com/" --feed "RPackages" --name "r-3.5.0" --version "1.0.4" --path . --debug
Command arguments: ['package', 'universal', 'download', '--instance', 'https://eedp.visualstudio.com/', '--feed', 'RPackages', '--name', 'r-3.5.0', '--version', '1.0.4', '--path', '.', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x03A88D20>, <function OutputProducer.on_global_arguments at 0x03B328E8>, <function CLIQuery.on_global_arguments at 0x03AE52B8>]
Event: CommandInvoker.OnPreCommandTableCreate [<function CLILogging.remove_logger_flags at 0x03A88D68>]
Event: CommandLoader.OnLoadCommandTable []
Event: CommandLoader.OnLoadArguments []
Event: CommandInvoker.OnPostCommandTableCreate []
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x03B32930>, <function CLIQuery.handle_query_parameter at 0x03AE5300>, <function VstsCLI.post_parse_args at 0x04533300>]
Universal Packages is currently in preview.
Checking for a new ArtifactTool
Checking for ArtifactTool updates
Getting credential: vsts-cli:https://eedp.visualstudio.com
Getting credential: vsts-cli: default
Creating connection with personal access token.
Telemetry enabled.
vsts._file_cache : Loading cache file: C:\Users\WillVinke\.vsts\python-sdk\cache\options.json
vsts._file_cache : attempting to read file C:\Users\WillVinke\.vsts\python-sdk\cache\options.json as utf-8-sig
vsts.vss_client : File cache hit for options on: https://eedp.visualstudio.com
vsts.vss_client : Route template: _apis/{area}/{resource}
vsts.vss_client : Api version '4.0-preview.1'
vsts.vss_client : POST https://eedp.visualstudio.com/_apis/CustomerIntelligence/Events
vsts.vss_client : Request content: [{'area': 'CLI', 'feature': 'package', 'properties': {'Command': 'universal download', 'Args': ['instance', 'feed', 'name', 'version', 'path']}}]
vsts._file_cache : Loading cache file: C:\Users\WillVinke\.vsts\python-sdk\cache\resources.json
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
vsts._file_cache : attempting to read file C:\Users\WillVinke\.vsts\python-sdk\cache\resources.json as utf-8-sig
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Evaluate proxies against ENV settings: True
vsts.vss_connection : File cache hit for resources on: https://eedp.visualstudio.com
Looking up current version of ArtifactTool...msrest.pipeline : Configuring redirects: allow=True, max=30

vsts.vss_client : File cache hit for options on: https://eedp.vsblob.visualstudio.com
msrest.pipeline : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
vsts.vss_client : Route template: _apis/{area}/{toolName}/{resource}
vsts.vss_client : Api version '5.0-preview'
urllib3.connectionpool : Starting new HTTPS connection (1): eedp.visualstudio.com:443
vsts.vss_client : GET https://eedp.vsblob.visualstudio.com/_apis/clienttools/ArtifactTool/release?osName=Windows&arch=AMD64
vsts.vss_client : Request content: None
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
urllib3.connectionpool : Starting new HTTPS connection (1): eedp.vsblob.visualstudio.com:443
urllib3.connectionpool : https://eedp.visualstudio.com:443 "POST /_apis/CustomerIntelligence/Events HTTP/1.1" 204 0
vsts.vss_client : Response content: b''
urllib3.connectionpool : https://eedp.vsblob.visualstudio.com:443 "GET /_apis/clienttools/ArtifactTool/release?osName=Windows&arch=AMD64 HTTP/1.1" 200 443
vsts.vss_client : Response content: b'{"name":"ArtifactTool","rid":"win10-x64","version":"0.2.74","uri":"https://vsblobprodscussu5shard1.vsblob.vsassets.io/artifacttool/artifacttool-win10-x64-Release_0.2.74.zip?sv=2017-04-17&sr=b&sig=n0GUREh6SRjp0I1qxX8o3IxJYb7P1oF1lKQH2O5PLBU%3D&spr=https&se=2018-11-14T20%3A00%3A03Z&sp=r&P1=1542225303&P2=11&P3=2&P4=4DkMTVZhwtz24UWUebM7rWE1IWtzUn4fCBZXXF%2fiALo%3d"}'
Checking if we already have ArtifactTool release 'ArtifactTool_win10-x64_0.2.74'
Not updating ArtifactTool because the current release already exists at 'C:\Users\WillVinke\.vsts\cli\tools\artifacttool\ArtifactTool_win10-x64_0.2.74'
Getting credential: vsts-cli:https://eedp.visualstudio.com
Getting credential: vsts-cli: default
Creating connection with personal access token.
Running external command: C:\Users\WillVinke\.vsts\cli\tools\artifacttool\ArtifactTool_win10-x64_0.2.74\artifacttool universal download --service https://eedp.visualstudio.com/ --patvar VSTS_ARTIFACTTOOL_PATVAR --feed RPackages --package-name r-3.5.0 --package-version 1.0.4 --path .
[WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\knack\invocation.py", line 172, in execute
    cmd_result = parsed_args.func(params)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\knack\commands.py", line 105, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\knack\commands.py", line 203, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\universal.py", line 62, in download_package
    return artifact_tool.download_universal(team_instance, feed, name, version, path)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\artifacttool.py", line 24, in download_universal
    return self.run_artifacttool(team_instance, ["universal", "download", "--service", team_instance, "--patvar", self.PATVAR, "--feed", feed, "--package-name", package_name, "--package-version", package_version, "--path", path], "Downloading")
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\artifacttool.py", line 44, in run_artifacttool
    proc = self._tool_invoker.run(command_args, new_env, initial_progress_message, self._process_stderr)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\external_tool.py", line 68, in run
    self.start(command_args, env)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\site-packages\vsts\cli\package\common\external_tool.py", line 38, in start
    env=env)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by eedpWillVinke** [comment]
It was a problem with my installation. I have been installing/uninstalling this a lot, and it looks like the file being looked for ( Running external command: C:\Users\WillVinke.vsts\cli\tools\artifacttool\ArtifactTool_win10-x64_0.2.74\artifacttool universal download --service https://eedp.visualstudio.com/ --patvar VSTS_ARTIFACTTOOL_PATVAR --feed RPackages --package-name r-3.5.0 --package-version 1.0.4 --path .) was messed up in some way even thought the file was still there. I was able to fix the problem by just deleting the /[User]/.vsts directory then reinstalling.

Thanks, sorry for the confusion.
