### ISSUE TITLE
Cannot call create_work_item in CLI with fields containing "=" sign

### ISSUE THREAD

**Issue by jfthuong** [Microsoft/vsts-cli#243]
The variable `fields` for functions `create_work_item` and `update_work_item` is a list if strings `"<param>=<value>"`, but is referenced in several places (docstring and error message) as a `Space separated "field=value"` (see file *cli\work\common\work_item.py*).

Moreover, the code `kvp = field.split("=")` prevents using a value with `=` sign (like in Test Steps that use XML code): it would be better to add a limitation: `kvp = field.split("=", 1)`.

**Comment by tedchamb** [comment]
The functions `create_work_item` and `update_work_item` from cli\work\common\work_item.py are not meant to be called outside the cli.  The docstring and error messages are used for display purposes on the command line.  

if you want to create or update a work item from a python script, then call the [python sdk](https://github.com/Microsoft/azure-devops-python-api) directly.  You can find these methods here:

https://github.com/Microsoft/azure-devops-python-api/blob/51ebc471b13b583b13cf5bc3b891bc2b2573759d/vsts/vsts/work_item_tracking/v4_1/work_item_tracking_client.py#L1216

The second issue you mentioned, regarding the split is a bug.  Thanks for reporting it.

**Comment by jfthuong** [comment]
For the first point, I understand now: you use docstrings for generating documentation on usage of CLI.

It is funny that you redirect me to the SDK because I came upon this lines of code in the CLI while I was trying to figure out how to use the functions in *work_item_tracking_client.py*  😄

**Comment by ishitam8** [comment]
Fields value can now have '='  as well. Thanks @jfthuong  for reporting this. You should be able to see the changes in next release.

**Comment by atbagga** [comment]
Fixed in version 0.1.4.
