### ISSUE TITLE
Allow output column configuration

### ISSUE THREAD

**Issue by grork** [Microsoft/vsts-cli#80]
When using table or tsv output, I'd like to be able to configure the output columns, rather than having the fixed set of columns. Ideally, i can also set these on command by command basis.

**Comment by tedchamb** [comment]
Try the --query argument that allows you to use jmespath to have complete control over your output.  

[JMESPath tutorial](http://jmespath.org/tutorial.html)

Here is an example where we run the `code pr list` command and request a table with just the pull request ID, and the status column:

`vsts code pr list --query "[].{ID: pullRequestId, Status: status}" -o table`

output:
```
   ID  Status
------  --------
281549  active
281548  active
281547  active
281546  active
281543  active
```

**Comment by willsmythe** [comment]
@grork - you can do this using the `--query` argument. See http://jmespath.org for reference. 

Here is a quick example:
```
vsts code pr list \
     --query "[].[pullRequestId, title, lastMergeCommit.commitId]" --top 5 --out table
```

This results in output like this:
```
  Column1  Column2                                                                            Column3
---------  ---------------------------------------------------------------------------------  ----------------------------------------
   281554  Deploy SU0 to its new Cloud name (+'d') for cluster move                           50b3d140b820a6ab226f3644b7d5a23165e93915
. . . 
```

@elbatk - can you add this to the samples you are working on?

@tedchamb  - can you investigate why re-labeling columns isn't working as expected (CLI fails with a ? Accoding to the jmespath reference (and Azure CLI examples), this should work:

```
git pr list --query "[].{ID:pullRequestId,Title:title,Commit:lastMergeCommit.commitId}" --top 5 --out table
```

Note the `{  }` wrapping the column set in this example vs. the `[  ]` wrapping the example above.

Longer term, we should think about a simplified argument that lets the caller indicate the "columns" to show in the result set (and ordering of those columns). The value can be a comma or space separate list  of named data fields (or paths to fields?).

**Comment by tedchamb** [comment]
@willsmythe see my comment above on how to do columns.

We should provide ability to set the default --query value in the config for each command.

**Comment by willsmythe** [comment]
@tedchamb - makes sense.

**Comment by geverghe** [comment]
I see that the question has been answered and the corresponding documentation update has been done. Including the link to the documentation - [https://docs.microsoft.com/en-us/cli/vsts/format-output?view=vsts-cli-latest#using-the-table-option](https://docs.microsoft.com/en-us/cli/vsts/format-output?view=vsts-cli-latest#using-the-table-option) for reference. 

Closing this issue.
