### ISSUE TITLE
Version numbers are not consistent

### ISSUE THREAD

**Issue by austin-best** [Microsoft/vsts-cli#89]
When attempting to find the version of installed VSTS CLI, I stumbled across the command `vsts -v`.
It returned a higher (correct?) version number than when running `vsts` by itself:
![image](https://user-images.githubusercontent.com/22735659/33077466-25b754a2-ce8d-11e7-8561-441be1955e83.png)

As a side note, I couldn't find any documentation about `vsts -v`.

**Comment by tedchamb** [comment]
This is fixed in the dev branch.

@elbatk Can we add a documentation topic on the --version command?
