### ISSUE TITLE
PowerShell CLI extension

### ISSUE THREAD

**Issue by bergmeister** [Microsoft/vsts-cli#96]
I have created a first working prototype in my GitHub repo [here](https://github.com/bergmeister/posh-vsts-cli) that brings the `vsts-cli` to `PowerShell` by extending its functionality to
- parsing the output of the cli to objects so that one can easily access each property
- providing tab completion

I was thinking of creating a PR to add it to your `README.md` in something like a `3rd party extensions/tools` section.
What do you think?

**Comment by tedchamb** [comment]
Very cool!  I'm eager to give this a try when I get a chance.  Let me get back to you on this.

**Comment by wnjenkin** [comment]
@bergmeister thanks for creating this extension! Once @tedchamb reviews your prototype, we should add this to the Visual Studio Marketplace (https://marketplace.visualstudio.com/) as an integration with a pointer to your github repo. Here is an example of an integration we support today - https://marketplace.visualstudio.com/items?itemName=ms-vsts.vss-services-slack

**Comment by bergmeister** [comment]
@wnjenkin I have published it to the PSGallery in the meantime, which is the central place for PowerShell modules: https://www.powershellgallery.com/packages/posh-vsts-cli/1.1.4
