### ISSUE TITLE
Support for showing Release build results

### ISSUE THREAD

**Issue by bergmeister** [Microsoft/vsts-cli#98]
I'd need to have the equivalent of an `vsts release list` command

**Comment by tedchamb** [comment]
I assume you are referring to release management commands?

**Comment by bergmeister** [comment]
Yes, because I use release management for CI system tests that are end to end and therefore seeing the results would be great. I know I could always fall back to the REST API but the vsts-cli would make it much easier.

**Comment by atbagga** [comment]
This is released in new version 0.1.4

**Comment by bergmeister** [comment]
@atbagga Thanks but I cannot see the new release either [here](https://github.com/Microsoft/vsts-cli/releases) or from the download link `https://aka.ms/vsts-cli-windows-installer` of the docs site [here](https://docs.microsoft.com/en-us/cli/vsts/install?view=vsts-cli-latest)

**Comment by atbagga** [comment]
My bad. Updated here early. 
Release is available now. Docs should be updated soon. Keeping the issue open for now.

**Comment by atbagga** [comment]
@bergmeister  The new release and docs are out. Please take a look and provide feedback.
